#Spring Config
spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      authentication-database: admin
#      username: rootUser
#      password: rootPassword
      database: admin
  mvc:
    throw-exception-if-no-handler-found: true
  resources:
    add-mappings: false
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
        

# Logging Config
logging:
  level:
    web: debug
    org:
      springframework:
        security: error
        web: debug
        data:
          mongodb:
            core:
              MongoTemplate: debug

# Server Config
server:
  port: 8085
